#+TITLE: Daily Notes Tuesday, 29/10/2019

** [[http://pages.cs.wisc.edu/~remzi/Naur.pdf][link]] - A piece by Peter Naur                           :philosophy:
This piece was about how Programming is not about building programs, but about gaining an insight into the problem and developing theories for that domain.
He eloquently conveys the message about how programmers even though they work with computers cannot be treated as computers.
A brilliant piece worth another thorough read.
** [[https://blog.acolyer.org/2019/10/25/task-based-effectiveness-of-basic-visualizations/][link]] - Preferred Visual representations              :presentation:
summary -
bar graphs for clusters
line graphs for correlations
scatter plots for anomolies
avoid line charts to identify precise data point
avoid pie and table charts for correlations
** [[https://blog.acolyer.org/2019/10/23/futzing-and-moseying/][link]] - Interview with professional data analysts   :data_analytics:
A nice insight into the life of data analyst, as expected, the biggest pain point is clients not being aware of their requirements.
Technical challanges with EDA are the initail stages take a lot of time.
Learned about notebooks for data analatics - Apache Zeppelin, Jupyter notebooks etc.
** read about P-values, multiple comparision problem, simpson's paradox a very interesting statistical bias.
Spend more time on this
** [[http://web.stanford.edu/class/cs240/readings/89-leases.pdf][link]] - read about leases, a way of maintaining distributed cache in fault tolerant manner :distributed_system:cache:
performace wise I can see some huge benefits but I have some doubts about the consistency it can maintain, 
